# -*- coding: utf-8 -*-
"""Agente 2_3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qt96wT97Db3q2xuEHOacEYSC1EjQbBEA
"""

!pip install pandas scikit-learn transformers torch accelerate

import pandas as pd
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, LabelEncoder

class AgenteNormalizador:

    def procesar(self, archivo_csv):

        df = pd.read_csv(archivo_csv)

        # Eliminar duplicados
        df = df.drop_duplicates()

        # Completar valores faltantes numéricos
        num_cols = df.select_dtypes(include=['int64','float64']).columns

        if len(num_cols) > 0:
            imputer = SimpleImputer(strategy="mean")
            df[num_cols] = imputer.fit_transform(df[num_cols])

            scaler = StandardScaler()
            df[num_cols] = scaler.fit_transform(df[num_cols])

        # Codificar variables categóricas
        cat_cols = df.select_dtypes(include=['object']).columns

        for col in cat_cols:
            encoder = LabelEncoder()
            df[col] = encoder.fit_transform(df[col])

        return df

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

class AgenteEntrenador:

    def entrenar(self, df, target):

        X = df.drop(columns=[target])
        y = df[target]

        X_train, X_test, y_train, y_test = train_test_split(
            X, y,
            test_size=0.2,
            random_state=42
        )

        modelo = RandomForestClassifier()

        modelo.fit(X_train, y_train)

        pred = modelo.predict(X_test)

        accuracy = accuracy_score(y_test, pred)

        metricas = {
            "accuracy": accuracy
        }

        return modelo, metricas

from transformers import pipeline

class AgenteReportero:

    def __init__(self):

        self.llm = pipeline(
            "text-generation",
            model="distilgpt2"
        )

    def generar_reporte(self, metricas):

        prompt = f"""
        Genera un reporte profesional.

        Accuracy: {metricas['accuracy']}
        """

        resultado = self.llm(
            prompt,
            max_new_tokens=100
        )

        return resultado[0]["generated_text"]

normalizador = AgenteNormalizador()
entrenador = AgenteEntrenador()
reportero = AgenteReportero()

from google.colab import files

uploaded = files.upload()

df = normalizador.procesar("sales_data_normalizado.csv")

print(df.columns)

print(list(df.columns))

target="aprobado"

# Usamos el reportero para generar el informe final
reporte = reportero.generar_reporte(metricas)
print(reporte)

print(df['STATUS'].unique())

# Now we train using the correct column 'STATUS' identified earlier
modelo, metricas = entrenador.entrenar(
    df,
    target='STATUS'
)
print("Entrenamiento completado.")
print(f"Métricas: {metricas}")