# -*- coding: utf-8 -*-
"""Agente 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qt96wT97Db3q2xuEHOacEYSC1EjQbBEA
"""

!pip install pandas scikit-learn transformers torch accelerate

import pandas as pd
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, LabelEncoder

class AgenteNormalizador:

    def procesar(self, archivo_csv):

        df = pd.read_csv(archivo_csv)

        # Eliminar duplicados
        df = df.drop_duplicates()

        # Completar valores faltantes numéricos
        num_cols = df.select_dtypes(include=['int64','float64']).columns

        if len(num_cols) > 0:
            imputer = SimpleImputer(strategy="mean")
            df[num_cols] = imputer.fit_transform(df[num_cols])

            scaler = StandardScaler()
            df[num_cols] = scaler.fit_transform(df[num_cols])

        # Codificar variables categóricas
        cat_cols = df.select_dtypes(include=['object']).columns

        for col in cat_cols:
            encoder = LabelEncoder()
            df[col] = encoder.fit_transform(df[col])

        return df