# -*- coding: utf-8 -*-
"""Modelo ilm

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Bjujybp2BNno2I1xfQcEb7wJ-ZPezrIk
"""

from google.colab import files

uploaded = files.upload()

import pandas as pd

df = pd.read_csv('sales_data_normalizado.csv')

df.head()

print(df.shape)

print(df.columns)

df.info()

!pip install sentence-transformers faiss-cpu transformers